stages:
- build
- release

build:
  image: dbogatov/docker-images:gulp-bower-latest
  stage: build
  script:
  - ./build.sh
  artifacts:
    expire_in: 30 min
    paths:
    - "app/"
	- "config/"
	- "public/"
	- "node_modules/"
	- "app.js"
  tags:
  - docker

dockerify:
  stage: release
  dependencies:
  - build
  script:
  - docker build -t registry.dbogatov.org/dbogatov/cs-3043-group-project .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.dbogatov.org
  - docker push registry.dbogatov.org/dbogatov/cs-3043-group-project
  tags:
  - shell
